saras_analytics:
  outputs:
    dev:
      dataset: derived_saras_analytics
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: ../bigquery_key.json
      location: US
      method: service-account
      priority: interactive
      project: tomrockdsouza
      threads: 1
      type: bigquery
  target: dev
